id: I684894EA
legacy_id: P009312
ocr_import_info:
  bdrc_scan_id: W1KG17592
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T11:51:42'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:40:26.650621+00:00'
last_modified: 2022-08-31 17:40:35.270286
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17592
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17592
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀུན་རིག་གི་ཆོ་ག་གཞན་ཕན་མཐའ་ཡས་དང་། དེ་ལ་ཉེ་བར་མཁོ་བའི་ཆོ་གའི་ཡན་ལག་དུ་མ་དང་བཅས་པ།
  author: འཇམ་མགོན་ཨ་མེས་ཞབས།
statistics:
  ocr_word_mean_confidence_index: 0.8549843429501381
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG17975:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17975
      total_pages: 178
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17975.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8549843429501381
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
