id: P009312
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17592
  title: ཀུན་རིག་གི་ཆོ་ག་གཞན་ཕན་མཐའ་ཡས་དང་། དེ་ལ་ཉེ་བར་མཁོ་བའི་ཆོ་གའི་ཡན་ལག་དུ་མ་དང་བཅས་པ།
  author: ''
  volumes:
    9a98e977e3c043e8ba9d2afe9431c934:
      image_group_id: I1KG17975
      title: ''
      volume_number: 1
      total_pages: 178
      base_file: v001.txt
