id: opecha:P009312
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17592
  title: ཀུན་རིག་གི་ཆོ་ག་གཞན་ཕན་མཐའ་ཡས་དང་། དེ་ལ་ཉེ་བར་མཁོ་བའི་ཆོ་གའི་ཡན་ལག་དུ་མ་དང་བཅས་པ།
  volume: ''
  author: ''
